setwd("C:/Users/alex.abraham/Documents/Coursera R")

#HungerData <- read.csv("hunger.csv")
#hist(HungerData$Numeric,col="red")
#hist(HungerData$Numeric,breaks=100,col="green")

#dens <-(HungerData$Numeric)
#plot(HungerData$Numeric, HungerData$SEX, pch=19, col="blue", cex=.5)
#image(1:10,161:236,as.matrix(pData[1:10,161:236]))
#x <- c(NA, NA, NA, 4,5,6,7,8,9,1)
#plot(x,y,pch=19,xlim=c(0,11),ylim=c(0,11))
#x <- rnorm(100)
#y <- rnorm(100)
#y[x<0]<- NA
#boxplot(x~is.na(y))
#plot(pData$WGTP, pData$wgtp2, pch=19, col="blue",cex=.5,xlab="Travel time(min)",ylab="Last 12 month wages(dollars)")
#par (mfrow=c(1,2))
# plot(pData$WGTP, pData$wgtp2, pch=19, col="blue",cex=.5,xlab="Travel time(min)",ylab="Last 12 month wages(dollars)")
#hist(pData$WGTP, pData$wgtp2, breaks=100)
#set.seed(1234); par(mar=c(0,0,0,0))
#x<- rnorm(12, mean=rep(1:3,each=4),sd=.2)
#y<- rnorm(12, mean=rep(1,2,1,each=4),sd=.2)
#plot(x,y,col="blue",pch=19,cex=2)
#text(x+0.05,y+0.05,labels=as.character(1:12))
#dataFrame<-data.frame(x=x,y=y)
#dist(dataFrame)
#distxy<-dist(dataFrame)
#hClustering<-hclust(distxy)
#plot(hClustering)
#kmeansobj <-kmeans(dataFrame,centers=3)
#names(kmeansobj)
#set.seed(12345)
#dataMatrix<-matrix(rnorm(400),nrow=40)
#dataMatrix
#set.seed(678910)
#for(i in 1:40){
  #flip a coin
#  coinFlip <-rbinom(1,size=1,prob=.5)
  #if coin is heads add a common pattern to that row
 # if(coinFlip){
  #  dataMatrix[i,]<- dataMatrix[i,]+rep(c(0,3),each=5)
  #}
#}
#image(1:10,1:40,t(dataMatrix)[,nrow(dataMatrix):1])
#h<-hclust(dist(dataMatrix))
#dataMatrixOrdered<-dataMatrix[hh$order]
# image(t(dataMatrixOrdered)[,nrow(dataMatrixOrdered):1])
#plot(rowMeans(dataMatrixOrdered),40:1,,xlab="Row",ylab="Row Mean",pch=19)
# plot(colMeans(dataMatrixOrdered),xlab="Column",ylab="Column Mean",pch=19)
# svd1<-svd(scale(dataMatrixOrdered))
#plot(svd1$u[,1],40:1,,xlab="Row",ylab="First Left Singular Vector",pch=19)
#plot(svd1$v[,1],xlab="Row",ylab="First Right Singular Vector",pch=19)
#plot(svd1$d,xlab="Column",ylab="Singular Value",pch=19)
# plot(svd1$d^2/sum(svd1$d^2),xlab="Column",ylab="Percent of variance explained",pch=19)
# plot(pca1$rotation[,1],svd1$v[,1],pch=19,xlab="Principal comp 1",ylab="Right singular val 1")
#abline(c(0,1))
#library(UsingR)
# par(mfrow=c(1,2))
# data(galton)
# hist(galton$child,col="blue",breaks=100)
# hist(galton$parent,col="blue",breaks=100)
# meanC <-mean(galton$child)

#lines(rep(meanC,100),seq(0,150,length=100),col="red",lwd=5)
# lines(rep(meanC,100),seq(0,150,length=100),col="red",lwd=5)
#plot(galton$parent,galton$child,pch=12,col="green")
#lm1<-lm(galton$child~galton$parent)
#lines(galton$parent,lm1$fitted,col="brown",lwd=5)
# plot(x,dt(x,df=(928-2)),col="blue",lwd=3,type="l")
#arrows(summary(lm1)$coeff[2,3],.25,summary(lm1)$coeff[2,3],0,col="red",lwd=4)
# xSeq <- c(seq(summary(lm2)$coeff[2,3],5,length=10),summary(lm2)$coeff[2,3])
#ySeq <- c(dt(seq(summary(lm2)$coeff[2,3],5,length=10),df=8),0)
#polygon(xSeq,ySeq,col="red")
#polygon(-xSeq,ySeq,col="red")
#movies <- read.table("./data/movies.txt",sep="\t",header =T, quote="")
#meanRatings <- tapply(movies$score, movies$rating, mean)
# points(1:4,meanRatings,col="red",pch="-",cex=5)
#lm1 <-lm(movies$score ~ as.factor(movies$rating))
#summary(lm1)
#confint(lm1)
#lm2<-lm(movies$score~relevel(movies$rating,ref="R"))
#anova(lm1)
#lm1 <-aov(movies$scores ~ as.factor(movies$ratings))
#TukeyHSD(lm1)
#aovObject2 <- aov(movies$score ~ movies$rating + movies$genre)
# aovobject2
# aovObject$coeff

# summary(aovObject2)
#download.file("https://dl.dropbox.com/u/7710864/data/ravensData.rda",destfile="./data/ravensData.rda")
##> download.file("https://dl.dropbox.com/u/7710864/data/gaData.rda",destfile="./data/gaData.rda")
#load("./data/gaData.rda")
#gaData$julian <- julian(gaData$date)
#> wBreaks <- anova(warpbreaks$breaks ~ warpbreaks$wool + warpbreaks$tension)
#anova(wBreaks)
#set.seed(12345)
# x <- rnorm(10)
# y <- rnorm(10)
# z <- rbinom(10,size=1,prob=.5)
# plot(x,y, col=(z+3), pch=19)
# par(mfrow=c(1,2))
# zhat <- (-.2<y)&(y<.6)
# plot(x,y,pch=19,col=(z+3))
# plot(x,y,pch=19,col=(zhat+3))
# set.seed(12333)
# x1 <- rnorm(10)
# y1 <- rnorm(10)
# par(mfrow=c(1,2))
# z1 <- rbinom(10,size=1,prob=.5)
# plot(x1,y1,pch=19,col=(z1+3))
# zhat1 <- (-.2<y)&(y<.6)
#> plot(x1,y1,pch=19,col=(zhat1+3))
#data(faithful)
# dim(faithful)
#set.seed(333)
# trainSamples<-sample(1:272,size=272/2,replace=F)
# trainFaith <- faithful[trainSamples,]
# testFaith <- faithful[-trainSamples,]
# head(trainFaith)
#plot(trainFaith$waiting,trainFaith$eruptions,pch=19,col="blue",xlab="Waiting", ylab="Duration")
#> lines(trainFaith$waiting,lm1$fitted,lwd=3)
#plot(testFaith$waiting,testFaith$eruptions,pch=19,col="blue",xlab="Waiting", ylab="Duration")
#> lines(trainFaith$waiting,predict(lm1,newData=testFaith),lwd=3)
#> sqrt(sum(lm1$fitted-trainFaith$eruptions)^2)
#> sqrt(sum(predict(lm1,newdata=testFaith)-testFaith$eruptions)^2)
#> plot(iris$Petal.Width, iris$Sepal.Width, pch=19,col=as.numeric(iris$Species))
#> tree1 <- tree(Species ~ Sepal.Width+Petal.Width,data=iris)
#> summary(tree1)
#plot(tree1)
#text(tree1)
# summary(samsungData[1:12])
# names(samsungData)
#> sum(duplicated(names(samsungData)))
# names <- names(samsungData)
# names <- gsub("\\()", "", names); names <- gsub("\\(", "_", names); names <- gsub("\\)", "", names)
#for(i in 1:3){
#for(j in 1:length(names)){
#  if(names[j] %in% names[j+1:length(names)]){
#    names[j] <- paste(names[j], as.character(i), sep="_")
#  }
#}
#}
# gsub("_1_2", "_2", names) -> names
#names(samsungData) <- names
#> samsungData <- data.frame(samsungData)
#> samsungTrain <- samsungData[samsungData$subject < 7,]
#> set.seed(1234)
#> library(tree)
#> tree <- tree(as.factor(activity) ~., data=samsungTrain)
#> summary(tree)
#> plot(tree)
#> text(tree)
#plot(cv.tree(tree, FUN=prune.tree, method="misclass"))

# cd4Data <- read.table("./data/cd4.data", col.names=c("time", "cd4", "age", "packs", "drugs", "sex", "cesd", "id"))
#cd4Data <- cd4Data[order(cd4Data$time),]
#library(splines)
#> install.packages('devtools')
#> library(devtools)
#install_github('medley', 'mewo2')
#ns1 <- ns(cd4Data$time, df=3)
#par(mfrow=c(1,3))
# plot(cd4Data$time,ns1[,1]);plot(cd4Data$time,ns1[,2]);plot(cd4Data$time,ns1[,3]);
# lm1 <- lm(cd4Data$cd4 ~ ns1)
# summary(lm1)